### ISSUE TITLE
Mime types issue

### ISSUE THREAD

**Issue by DingDeM** [makbn/JThumbnail#10]
Hello,

Just want to draw your attention to the typo in the 'MimeTypeDetector.java' file. In line 168 there is an unnecessary space character in the mime type " application/vnd.ms-powerpoint".

I take this opportunity to ask you is there any particular reason for omitting the mime type "application/vnd.ms-excel" from the getExtensionsCached method?

Thanks in advance for your answer.

**Comment by makbn** [comment]
Hi @DingDeM,
Thank you for pointing out the typo! I've fixed it. 
About your question, I honestly don't know right away, It's an old project and I need to review everything one more time to be able to answer your question properly.
